version: "3.9"

services:
  web:
    build: .
    ports:
      - 4000:3000
    environment:
      - BETTER_AUTH_SECRET
      - BETTER_AUTH_URL
      - DATABASE_URL
      - NODE_ENV
    command: sh -c "npx prisma migrate deploy && pnpm start"
