version: "3.9"

services:
  web:
    build: .
    ports:
      - 4000:3000
    environment:
      - HOST=0.0.0.0
      - BETTER_AUTH_SECRET
      - BETTER_AUTH_URL
      - DATABASE_URL
      - NODE_ENV
    command: pnpm start
