import './globals.css'

import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'

import MainLayout from '@/components/layouts/main-layout'
import TanstackProvider from '@/components/providers/tanstack-provider'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { Toaster } from '@/components/ui/sonner'

const outfitSans = Outfit({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${outfitSans.variable} antialiased`}>
        <TanstackProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <MainLayout>{children}</MainLayout>
          </ThemeProvider>
          <Toaster />
        </TanstackProvider>
      </body>
    </html>
  )
}
