name: CI/CD Pipeline

on:
  push:
    branches: [prod, staging]

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '8'

jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: TypeScript check
        run: pnpm ts:fix
        
      - name: Lint check
        run: pnpm lint
        
      - name: Run tests
        run: pnpm test:ci
        
      - name: Build application
        run: pnpm build
        
      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        env:
          DOKPLOY_API_KEY: ${{ secrets.DOKPLOY_API_KEY }}
          DOKPLOY_URL: ${{ secrets.DOKPLOY_URL }}
          STAGING_APP_ID: ${{ secrets.STAGING_APP_ID }}
        run: |
          curl -X 'POST' \
            '${{ env.DOKPLOY_URL }}/api/trpc/application.deploy' \
            -H 'accept: application/json' \
            -H 'x-api-key: ${{ env.DOKPLOY_API_KEY }}' \
            -H 'Content-Type: application/json' \
            -d '{
              "json": {
                "applicationId": "${{ env.STAGING_APP_ID }}"
              }
            }'
          
      - name: Deploy to Production
        if: github.ref == 'refs/heads/production'
        env:
          DOKPLOY_API_KEY: ${{ secrets.DOKPLOY_API_KEY }}
          DOKPLOY_URL: ${{ secrets.DOKPLOY_URL }}
          PRODUCTION_APP_ID: ${{ secrets.PRODUCTION_APP_ID }}
        run: |
          curl -X 'POST' \
            '${{ env.DOKPLOY_URL }}/api/trpc/application.deploy' \
            -H 'accept: application/json' \
            -H 'x-api-key: ${{ env.DOKPLOY_API_KEY }}' \
            -H 'Content-Type: application/json' \
            -d '{
              "json": {
                "applicationId": "${{ env.PRODUCTION_APP_ID }}"
              }
            }'